# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_USER: $MYSQL_ROOT_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes: 
  db-config:
  db-data: