version: '3.1'

# Settings and configurations that are common for minio containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2021-10-23T03-28-24Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
    client:
        build:
          context: ./client
        ports:
          - 3000:3000
        container_name: client
        restart: always
        command: npm run dev
        volumes:
           - ./client:/usr/src/app
           - /usr/src/app/node_modules
           
    server:
        build:
            context: ./server
        ports:
            - 4000:4000
        restart: always
        container_name: server
        env_file: 
          - ./.env
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        
    db:
      image: mariadb
      restart: always
      container_name: db
      ports:
        - 3306:3306
      environment:
          MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
          MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
          MYSQL_DATABASE: "publishing_engine_dev"
      volumes:
        - ./mysqldb:/var/lib/mysql
 
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080

    minio_storage:
      image: nginx:1.19.2-alpine
      hostname: nginx
      volumes:
        - ./data/nginx/minio.conf:/etc/nginx/nginx.conf:ro
      ports:
        - "9000:9000"
        - "9001:9001"
      depends_on:
        - minio1
        - minio2
        - minio3
        - minio4

    minio1:
      <<: *minio-common
      hostname: minio1
      volumes:
        - data1-1:/data1
        - data1-2:/data2
  
    minio2:
      <<: *minio-common
      hostname: minio2
      volumes:
        - data2-1:/data1
        - data2-2:/data2
  
    minio3:
      <<: *minio-common
      hostname: minio3
      volumes:
        - data3-1:/data1
        - data3-2:/data2
  
    minio4:
      <<: *minio-common
      hostname: minio4
      volumes:
        - data4-1:/data1
        - data4-2:/data2

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2: