version: '3.1'

# Settings and configurations that are common for minio containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2021-10-23T03-28-24Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
    nginx:
        image: nginx:1.15-alpine
        restart: unless-stopped
        container_name: nginx_server
        volumes:
          - ./data/nginx/app.conf:/etc/nginx/conf.d/app.conf
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot
        ports:
          - 80:80
          - 443:443
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  

    client:
        build:
          context: ./client
        ports:
          - 3000:3000
        container_name: client
        restart: always
        command: npm run start
        volumes:
          - ./client:/usr/src/app
          - /usr/src/app/node_modules

    server:
        build:
            context: ./server
        env_file: 
          - ./.env
        ports:
            - 4000:4000
        restart: always
        container_name: server
        volumes:
          - ./server:/usr/src/app
          - /usr/src/app/node_modules
          - ./data/certbot/conf:/etc/letsencrypt
        
    db:
      image: mariadb
      restart: always
      container_name: db
      ports:
        - 3306:3306
      environment:
          MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
          MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
          MYSQL_DATABASE: "publishing_engine_prod"
      volumes:
        - ./mysqldb:/var/lib/mysql
 
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080

    minio_storage:
      image: nginx:1.19.2-alpine
      hostname: nginx
      volumes:
        - ./data/nginx/sslminio.conf:/etc/nginx/nginx.conf:ro
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot

      ports:
        - "9000:9000"
        - "9001:9001"
      depends_on:
        - minio1
        - minio2
        - minio3
        - minio4

    minio1:
      <<: *minio-common
      hostname: minio1
      volumes:
        - data1-1:/data1
        - data1-2:/data2
  
    minio2:
      <<: *minio-common
      hostname: minio2
      volumes:
        - data2-1:/data1
        - data2-2:/data2
  
    minio3:
      <<: *minio-common
      hostname: minio3
      volumes:
        - data3-1:/data1
        - data3-2:/data2
  
    minio4:
      <<: *minio-common
      hostname: minio4
      volumes:
        - data4-1:/data1
        - data4-2:/data2

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2: